### ISSUE TITLE
Related work

### ISSUE THREAD

**Issue by karlkeefer** [aesrael/go-postgres-jwt-react-starter#12]
Just wanted to drop a link to my repo that is essentially the same thing, but with a helpful docker-compose wrapper for everything to make all of the dependencies a snap: https://github.com/karlkeefer/pngr/

**Comment by aesrael** [comment]
> Just wanted to drop a link to my repo that is essentially the same thing, but with a helpful docker-compose wrapper for everything to make all of the dependencies a snap: https://github.com/karlkeefer/pngr/

good stuff! also I am currently revamping the project in the spirit of hacktoberfest and will do just that. thank you!
